# Generated by Django 3.0.6 on 2020-05-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, help_text='Euro,cents', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('description', models.CharField(max_length=3000)),
                ('author', models.CharField(max_length=156)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Eqipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('eq_type', models.CharField(choices=[('Brewing', 'Brewing'), ('Cleaning', 'Cleaning'), ('Fermentation', 'Fermentation'), ('Botteling', 'Botteling')], default='Brewing', max_length=100)),
                ('description', models.CharField(max_length=3000)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Hops',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('alfa_acid', models.DecimalField(decimal_places=2, help_text='percent', max_digits=5)),
                ('beta_acid', models.DecimalField(decimal_places=2, help_text='percent', max_digits=5)),
                ('aroma', models.CharField(max_length=512)),
                ('use', models.CharField(max_length=512)),
                ('substitute', models.CharField(max_length=512)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('malt_type', models.CharField(choices=[('Base malt', 'Base malt'), ('Caramel and Crystal malt', 'Caramel and Crystal malt'), ('Roasted malts', 'Roasted malts'), ('Flaked and unmalted grains', 'Flaked and unmalted grains')], default='Base malt', max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('producer', models.CharField(max_length=156)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('dosage', models.CharField(max_length=156)),
                ('fermenting_temp', models.CharField(max_length=156)),
                ('pitching', models.CharField(max_length=156)),
                ('flocctuaition', models.CharField(max_length=156)),
                ('weight', models.CharField(max_length=156)),
            ],
            bases=('products.product',),
        ),
    ]
