# Generated by Django 3.0.6 on 2020-05-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200510_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hops',
            new_name='Hop',
        ),
    ]
